version: "3.7"
services:
  client: # second service
    container_name: client-container
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
    volumes:
      - .:/code
  mysql: # third service
    container_name: mysql-container
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    expose:
      - "3306"
    ports: 
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
